# Generated by Django 5.2.5 on 2025-10-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("region", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期（月）")),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="信息价"
                    ),
                ),
                (
                    "CategorySpecification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.categoryspecification",
                        verbose_name="规格",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                        verbose_name="物资类别",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="region.region",
                        verbose_name="地区",
                    ),
                ),
            ],
            options={
                "verbose_name": "指导价",
                "verbose_name_plural": "指导价",
                "db_table": "guide_price",
            },
        ),
    ]
