# Generated by Django 5.2.5 on 2025-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(max_length=255, verbose_name="项目名称"),
                ),
                ("region_id", models.IntegerField(verbose_name="指向地区id")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "Inactive"),
                            ("active", "Active"),
                            ("closed", "Closed"),
                        ],
                        max_length=10,
                        verbose_name="状态：inactive|active|closed",
                    ),
                ),
                (
                    "created_by",
                    models.IntegerField(verbose_name="创建者ID，关联USER表id"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "db_table": "project",
            },
        ),
    ]
