version: "3"
services:
  django-hbsz:
    build:
      context: .
      dockerfile: ./docker_env/django/Dockerfile
      args:
        - COMPOSE_DOCKER_CLI_BUILD=1
    container_name: django-hbsz
    working_dir: /backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: always
    volumes:
      - ./backend:/backend
      - ./docker_env/django/logs:/var/log