version: "3"
services:
  django-hbsz:
    build:
      context: .
      dockerfile: ./docker_env/django/Dockerfile
      args:
        - COMPOSE_DOCKER_CLI_BUILD=1  # 设置串行构建
    container_name: django-hbsz
    working_dir: /backend
    ports:
      - "8080:8080"
    expose:
      - "8080"
    restart: always
    volumes:
      - ./backend:/backend
      - ./docker_env/django/logs:/var/log
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_NAME=hbsz-vue3
      - DATABASE_USER=root
      - DATABASE_PASSWORD=123456

  web-hbsz:
    container_name: web
    ports:
      - "80:80"
    build:
      context: ./
      dockerfile: ./docker_env/web/Dockerfile
      args:
        - COMPOSE_DOCKER_CLI_BUILD=1  # 设置串行构建
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./docker_env/nginx/my.conf:/etc/nginx/conf.d/my.conf
