version: "3"
services:
  django:
    build:
      context: .
      dockerfile: ./docker_env/django/Dockerfile
      args:
        - COMPOSE_DOCKER_CLI_BUILD=1  # 设置串行构建
    container_name: django
    working_dir: /backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: always
    volumes:
      - ./backend:/backend
      - ./docker_env/django/logs:/var/log
    depends_on:
      - mysql
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_NAME=hbsz-vue3
      - DATABASE_USER=hbsz
      - DATABASE_PASSWORD=qwer1234
  
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hbsz-vue3
      MYSQL_USER: hbsz
      MYSQL_PASSWORD: qwer1234
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./backend/docker_init.sql:/docker-entrypoint-initdb.d/init.sql  # 可选：初始化脚本
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

  web:
    container_name: web
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: ./docker_env/web/Dockerfile
      args:
        - COMPOSE_DOCKER_CLI_BUILD=1  # 设置串行构建
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./docker_env/nginx/my.conf:/etc/nginx/conf.d/my.conf

volumes:
  mysql_data:
