version: "3"
services:
  web-hbsz:
    container_name: web-hbsz
    ports:
      - "80:80"
    build:
      context: ./
      dockerfile: ./docker_env/web/Dockerfile
      args:
        - COMPOSE_DOCKER_CLI_BUILD=1
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./docker_env/nginx/my.conf:/etc/nginx/conf.d/my.conf