# Generated by Django 5.2.5 on 2025-09-25 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification_name",
                    models.CharField(max_length=255, verbose_name="规格名称"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                        verbose_name="物资类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "规格",
                "verbose_name_plural": "规格",
            },
        ),
    ]
