# Generated by Django 5.2.5 on 2025-10-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=255, verbose_name="物资类别名称"),
                ),
            ],
            options={
                "verbose_name": "物资类别",
                "verbose_name_plural": "物资类别",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="CategorySpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification_name",
                    models.CharField(max_length=255, verbose_name="规格名称"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="category.category",
                        verbose_name="物资类别",
                    ),
                ),
            ],
            options={
                "verbose_name": "物资类别规格",
                "verbose_name_plural": "物资类别规格",
                "db_table": "category_specification",
                "unique_together": {("category", "specification_name")},
            },
        ),
    ]
