# Generated by Django 5.2.5 on 2025-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=255, verbose_name="物资类别名称"),
                ),
            ],
            options={
                "verbose_name": "物资类别",
                "verbose_name_plural": "物资类别",
            },
        ),
    ]
