# Generated by Django 5.2.5 on 2025-09-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplier", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="supplier",
            table="supplier",
        ),
    ]
