# Generated by Django 5.2.5 on 2025-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(max_length=255, verbose_name="品牌名称"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
            ],
            options={
                "verbose_name": "品牌",
                "verbose_name_plural": "品牌",
                "db_table": "brand",
            },
        ),
    ]
