# Generated by Django 5.2.5 on 2025-09-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brand", "0002_alter_brand_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="描述"),
        ),
    ]
