/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountFooter: typeof import('./src/components/layout/AccountFooter.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    BrandForm: typeof import('./src/components/brand/BrandForm.vue')['default']
    BrandList: typeof import('./src/components/brand/BrandList.vue')['default']
    Carousel: typeof import('./src/components/home/Carousel.vue')['default']
    CategoryList: typeof import('./src/components/category/CategoryList.vue')['default']
    DeleteConfirm: typeof import('./src/components/common/DeleteConfirm.vue')['default']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Features: typeof import('./src/components/home/Features.vue')['default']
    GuidePriceChart: typeof import('./src/components/guidePrice/GuidePriceChart.vue')['default']
    GuidePriceFilters: typeof import('./src/components/guidePrice/GuidePriceFilters.vue')['default']
    GuidePriceList: typeof import('./src/components/guidePrice/GuidePriceList.vue')['default']
    HomeHero: typeof import('./src/components/home/HomeHero.vue')['default']
    LogoHeader: typeof import('./src/components/common/LogoHeader.vue')['default']
    MobileNavigation: typeof import('./src/components/layout/MobileNavigation.vue')['default']
    OrdersList: typeof import('./src/components/orders/OrdersList.vue')['default']
    ProjectsList: typeof import('./src/components/projects/ProjectsList.vue')['default']
    RegionDetail: typeof import('./src/components/region/RegionDetail.vue')['default']
    RegionForm: typeof import('./src/components/region/RegionForm.vue')['default']
    RegionList: typeof import('./src/components/region/RegionList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNavigation: typeof import('./src/components/layout/SidebarNavigation.vue')['default']
    StatsCards: typeof import('./src/components/common/StatsCards.vue')['default']
    SupplierList: typeof import('./src/components/supplier/SupplierList.vue')['default']
    UserInfo: typeof import('./src/components/user/UserInfo.vue')['default']
  }
}
